before_script:
  - |
    if [[  $TRAVIS_BRANCH == 'clientBuild' && $TRAVIS_COMMIT_MESSAGE == *"[run deploy]"*  ]]; then
      echo "__INCREMENT_VERSION_NUMBER__"
      export PACKAGE_VERSION=$(npm version patch)
      npm install -g documentation
      npm run doc

    fi
#1224c2be85d445ec6ddb436cb07074344de86e1d  1224c2be85d445ec6ddb436cb07074344de86e1d
#1224c2be85d445ec6ddb436cb07074344de86e1d
#1b40f86d09b167693bbd72677f89d3b425363f9e
language: node_js
sudo: required
node_js:
  - "stable"
# travis call prepare
# Send coverage data to Coveralls
# Deploy terminusdb/terminus-client
after_script:
  - npm run coveralls-after

branches:
  only:
    - clientBuild
#script: if [[ $TRAVIS_COMMIT_MESSAGE == *"trigger build"* ]]; then mvn install ; fi ;

before_deploy:
  - |
    if [[ ! $TRAVIS_VAR ]]; then
      npm run build
      echo "___TRAVIS_VAR____"
      export TRAVIS_VAR="1.$TRAVIS_BUILD_NUMBER"

      echo $PACKAGE_VERSION
      git config --local user.name "Francesca-Bit"
      git config --local user.email "francesca@datachemist.com"
      git checkout -b tmp
      git commit --amend -m "[skip travis] version changed $PACKAGE_VERSION"
      git push https://Francesca-Bit:$GITHUB_TOKEN@github.com/terminusdb/terminus-client.git HEAD:clientBuild
      git tag -f -a "$PACKAGE_VERSION" -m "new version $PACKAGE_VERSION"

      export LAST_HASH=$(git rev-parse HEAD)
      echo $LAST_HASH
    fi

#git tag -f -a "$PACKAGE_VERSION" -m "new version $PACKAGE_VERSION"
#git remote set-url origin https://Francesca-Bit:$GITHUB_TOKEN@github.com/terminusdb/terminus-client.git


#[skip travis] commit_message dosen't work in this travis version
# - provider: pages
# skip-cleanup: true
# target-branch: master # Commit to master instead of gh-pages
# github-token: $GITHUB_TOKEN
# commit_message: "Deploy from travis [skip travis]"
# keep-history: true # By default, Travis uses push --force and wipes out commit history
# verbose: true
# on:
# branch: master

deploy:
  - provider: script
    skip_cleanup: true
    keep_history: true
    script: bash public_pages.sh
    on:
      branch: clientBuild 
      condition: $TRAVIS_COMMIT_MESSAGE == *"[run deploy]"*
  - provider: releases
    keep_history: true
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    file: package.json
    overwrite: true
    file_glob: true
    file: ./*
    on:
      branch: clientBuild 
      condition: $TRAVIS_COMMIT_MESSAGE == *"[run deploy]"* 
      
  #- provider: npm
  #  skip_cleanup: true
  #  email: "francesca@datachemist.com"
  #  api_key: $NPM_TOKEN__
  #  keep_history: true
  #  on:
  #    branch : clientBuild
  #    condition: $TRAVIS_COMMIT_MESSAGE == *"[run deploy]"*
