before_script:
  - npm install -g documentation
  - |
    if [[  $TRAVIS_BRANCH == 'master' && ! $TRAVIS_VAR ]]; then
      echo "__INCREMENT_VERSION_NUMBER__"
      npm version patch
    fi
  - export PACKAGE_VERSION=$(node -p -e "require('./package.json').version")

language: node_js
sudo: required
node_js:
  - "stable"
# travis call prepare
# Send coverage data to Coveralls
after_script:
  - npm run coveralls-after

branches:
  only:
    - dev
    - master

before_deploy:
  - |
    if [[ ! $TRAVIS_VAR ]]; then
      echo $TRAVIS_VAR
      echo $PACKAGE_VERSION
      npm run doc
      git config --local user.name "Francesca-Bit"
      git config --local user.email "francesca@datachemist.com"      
      git tag -f $PACKAGE_VERSION -m "new version $PACKAGE_VERSION"
    fi
  - export TRAVIS_VAR="1.$TRAVIS_BUILD_NUMBER"
  - echo $TRAVIS_VAR

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    local_dir: public_pages
    on:
      branch: master
  - provider: releases
    keep_history: true
    api_key: $GITHUB_TOKEN
    file: public_pages/*
    skip_cleanup: true
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email: "francesca@datachemist.com"
    api_key: $NPM_TOKEN
    keep_history: true
    on:
      branch : master
