before_script:
  - |
    if [[  $TRAVIS_BRANCH == 'clientBuild' && $TRAVIS_COMMIT_MESSAGE == *"[run deploy]"*  ]]; then
      echo "__INCREMENT_VERSION_NUMBER__"
      export PACKAGE_VERSION=$(npm version patch)
      npm install -g documentation
      npm run doc
    fi

language: node_js
sudo: required
node_js:
  - "stable"

# travis call prepare
# Send coverage data to Coveralls
# Deploy terminusdb/terminus-client
after_script:
  - npm run coveralls-after

branches:
  only:
    - clientBuild

before_deploy:
  - |
    if [[ ! $TRAVIS_VAR ]]; then
      npm run build
      echo "___TRAVIS_VAR____"
      export TRAVIS_VAR="1.$TRAVIS_BUILD_NUMBER"
      git commit --amend -m "[skip travis] version changed $PACKAGE_VERSION"
      git push https://${GITHUB_TOKEN}@github.com/$TRAVIS_REPO_SLUG HEAD:$TRAVIS_BRANCH
      git tag -f -a "$PACKAGE_VERSION" -m "new version $PACKAGE_VERSION"
      export LAST_HASH=$(git ls-remote https://github.com/$TRAVIS_REPO_SLUG $TRAVIS_BRANCH | awk '{ print $1}')
      echo $LAST_HASH
    fi

deploy:
  - provider: script
    skip_cleanup: true
    keep_history: true
    script: bash public_pages.sh
    on:
      branch: clientBuild 
      condition: $TRAVIS_COMMIT_MESSAGE == *"[run deploy]"*
  - provider: releases
    target_commitish : $LAST_HASH
    keep_history: true
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    overwrite: true
    on:
      branch: clientBuild 
      condition: $TRAVIS_COMMIT_MESSAGE == *"[run deploy]"*  
  - provider: npm
    registry: "https://registry.npmjs.org/"
    skip_cleanup: true
    access: public
    email: "francesca@datachemist.com"
    api_key: $NPM_TOKEN
    keep_history: true
    auth_method: "authToken"
    on:
      branch : clientBuild
      condition: $TRAVIS_COMMIT_MESSAGE == *"[run deploy]"*
