language: node_js
sudo: required
node_js:
  - "stable"

stages:
  - build
  - deploy_dev
    if: branch = v2.0

jobs:
  include:
    - stage: build
      script:
        - npm ci
        - npm test

    - stage: deploy_dev
      script:
        - gem install package_cloud
        - bash .ci/publish_dev.sh

# travis call prepare
# Send coverage data to Coveralls
# Deploy terminusdb/terminus-client
after_script:
  - npm run coveralls-after

branches:
  only:
    - master
    - dev
    - v2.0

before_deploy: gem install package_cloud

deploy:
  - provider: script
    skip_cleanup: true
    keep_history: true
    script: bash public_pages.sh
    on:
      branch: master
      condition: $TRAVIS_COMMIT_MESSAGE == *"[run deploy]"*

  - provider: releases
    target_commitish : $LAST_HASH
    keep_history: true
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    overwrite: true
    on:
      branch: master 
      condition: $TRAVIS_COMMIT_MESSAGE == *"[run deploy]"*  
  - provider: npm
    registry: "https://registry.npmjs.org/"
    skip_cleanup: true
    access: public
    email: "francesca@datachemist.com"
    api_key: $NPM_TOKEN
    keep_history: true
    auth_method: "authToken"
    on:
      branch : master
      condition: $TRAVIS_COMMIT_MESSAGE == *"[run deploy]"*
