before_script:
  - npm install -g documentation
  - if [[  $TRAVIS_BRANCH == 'master' && !$TRAVIS_TAG ]]; then npm version patch; fi

language: node_js
sudo: required
node_js:
  - "stable"
# travis call prepare
# Send coverage data to Coveralls
after_script:
  - npm run coveralls-after

branches:
  only:
    - dev
    - master
#git remote add origin https://Francesca-Bit:$GITHUB_TOKEN@github.com/terminusdb/terminus-client.git
before_deploy:
  - |
    if ![[ $TRAVIS_TAG ]]; then
      echo "__BEFORE__TRAVIS__TAG__"
      export TRAVIS_TAG="1.$TRAVIS_BUILD_NUMBER" 
      echo $TRAVIS_TAG
      npm run doc 
      git config --local user.name "Francesca-Bit"
      git config --local user.email "francesca@datachemist.com"
      echo "__ADD_PACKAGE__ TO MASTER"
      git add package.json
      git commit -m "version changed travis_build_number $TRAVIS_TAG"
      git push origin master
      npm run git-tag;
    fi

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    local_dir: public_pages
    on:
      branch: master
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: public_pages/dist/*
    skip_cleanup: true
    on:
      branch: master
      condition: tag IS present
  - provider: npm
    skip_cleanup: true
    email: "francesca@datachemist.com"
    api_key: "$NPM_TOKEN"
    keep_history: true
    on:
      branch : master
      condition: tag IS present
