name: Build and release on production
on:
  push:
    branches:
      - dev
      - canary
      - rc
      - master

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Extract branch name
      shell: bash
      run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm install
    - run: npm run build
    - run: npm run coveralls-after
    - run: bash ".ci/publish_$BRANCH_NAME.sh"
