name: Build and release on production
on:
  push:
    branches:
      - dev
      - canary
      - rc
      - master

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Set up bintray
      run:
        |
          curl -u "rrooij:$BINTRAY_API_TOKEN" https://api.bintray.com/npm/terminusdb/npm-dev/auth > .npmrc
          echo "@terminusdb:$(cat .npmrc)" > .npmrc
    - run: npm install
    - run: npm run build
    - run: bash ".ci/publish_${GITHUB_REF##*/}.sh"
